 // This file has been generated by Specta. DO NOT EDIT.

export type AppData = { state: string; count: number }

export type TauRpcApiInputTypes = { proc_name: "update_state"; input_type: { __taurpc_type: string } } | { proc_name: "get_window"; input_type: null } | { proc_name: "get_app_handle"; input_type: null } | { proc_name: "test_io"; input_type: { __taurpc_type: AppData } } | { proc_name: "test_option"; input_type: null } | { proc_name: "test_result"; input_type: { __taurpc_type: AppData } } | { proc_name: "with_sleep"; input_type: null } | { proc_name: "method_with_alias"; input_type: null } | { proc_name: "ev"; input_type: { __taurpc_type: string } } | { proc_name: "vec_test"; input_type: { __taurpc_type: string[] } } | { proc_name: "multiple_args"; input_type: [string[], string] } | { proc_name: "increase_count"; input_type: null } | { proc_name: "get_app_data"; input_type: null }

export type TauRpcApiOutputTypes = { proc_name: "update_state"; output_type: null } | { proc_name: "get_window"; output_type: null } | { proc_name: "get_app_handle"; output_type: null } | { proc_name: "test_io"; output_type: AppData } | { proc_name: "test_option"; output_type: null | null } | { proc_name: "test_result"; output_type: AppData } | { proc_name: "with_sleep"; output_type: null } | { proc_name: "method_with_alias"; output_type: null } | { proc_name: "ev"; output_type: null } | { proc_name: "vec_test"; output_type: null } | { proc_name: "multiple_args"; output_type: null } | { proc_name: "increase_count"; output_type: null } | { proc_name: "get_app_data"; output_type: AppData }

export type TauRpcEventsInputTypes = { proc_name: "test_ev"; input_type: null } | { proc_name: "state_changed"; input_type: { __taurpc_type: string } } | { proc_name: "data_changed"; input_type: { __taurpc_type: AppData } } | { proc_name: "vec_test"; input_type: { __taurpc_type: string[] } } | { proc_name: "multiple_args"; input_type: [number, string[]] }

export type TauRpcEventsOutputTypes = { proc_name: "test_ev"; output_type: null } | { proc_name: "state_changed"; output_type: null } | { proc_name: "data_changed"; output_type: null } | { proc_name: "vec_test"; output_type: null } | { proc_name: "multiple_args"; output_type: null }

export type TauRpcUiApiInputTypes = { proc_name: "trigger"; input_type: null } | { proc_name: "test_ev"; input_type: null }

export type TauRpcUiApiOutputTypes = { proc_name: "trigger"; output_type: null } | { proc_name: "test_ev"; output_type: null }

const ARGS_MAP = {"events":"{\"vec_test\":[\"args\"],\"multiple_args\":[\"arg1\",\"arg2\"],\"state_changed\":[\"new_state\"],\"data_changed\":[\"new_data\"],\"test_ev\":[]}","":"{\"get_app_handle\":[],\"multiple_args\":[\"arg\",\"arg2\"],\"update_state\":[\"new_value\"],\"test_io\":[\"user\"],\"get_app_data\":[],\"test_result\":[\"user\"],\"vec_test\":[\"arg\"],\"with_sleep\":[],\"test_option\":[],\"ev\":[\"updated_value\"],\"increase_count\":[],\"get_window\":[],\"method_with_alias\":[]}","api.ui":"{\"trigger\":[],\"test_ev\":[]}"}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'': [TauRpcApiInputTypes, TauRpcApiOutputTypes],
	'events': [TauRpcEventsInputTypes, TauRpcEventsOutputTypes],
	'api.ui': [TauRpcUiApiInputTypes, TauRpcUiApiOutputTypes],
}